title: Python for Health, Economic, and Social Data Science
logo: assets/logo1.png
description: Welcome to the Python for Health, Economic, and Social Data Science homepage!
show_downloads: false
theme: jekyll-theme-minimal
